//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6407
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using org.sola.webservices.digitalarchive.extra;
namespace org.sola.webservices.digitalarchive.extra
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/faults/")]
    public partial class faultInfoBean : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string faultIdField;
        
        private string messageCodeField;
        
        private string[] messageParametersField;
        
        private validationResult[] validationResultListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string faultId
        {
            get
            {
                return this.faultIdField;
            }
            set
            {
                this.faultIdField = value;
                this.RaisePropertyChanged("faultId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string messageCode
        {
            get
            {
                return this.messageCodeField;
            }
            set
            {
                this.messageCodeField = value;
                this.RaisePropertyChanged("messageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messageParameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string[] messageParameters
        {
            get
            {
                return this.messageParametersField;
            }
            set
            {
                this.messageParametersField = value;
                this.RaisePropertyChanged("messageParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("validationResultList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public validationResult[] validationResultList
        {
            get
            {
                return this.validationResultListField;
            }
            set
            {
                this.validationResultListField = value;
                this.RaisePropertyChanged("validationResultList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/transferobjects/")]
    public partial class validationResult : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string feedbackField;
        
        private string nameField;
        
        private string severityField;
        
        private bool successfulField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string feedback
        {
            get
            {
                return this.feedbackField;
            }
            set
            {
                this.feedbackField = value;
                this.RaisePropertyChanged("feedback");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool successful
        {
            get
            {
                return this.successfulField;
            }
            set
            {
                this.successfulField = value;
                this.RaisePropertyChanged("successful");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/transferobjects/digitalarchive/")]
    public partial class documentBinaryTO : documentTO
    {
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentBinaryTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/transferobjects/digitalarchive/")]
    public partial class documentTO : abstractIdTO
    {
        
        private string descriptionField;
        
        private string extensionField;
        
        private string nrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nr
        {
            get
            {
                return this.nrField;
            }
            set
            {
                this.nrField = value;
                this.RaisePropertyChanged("nr");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentBinaryTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/transferobjects/")]
    public partial class abstractIdTO : abstractVersionedTO
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractIdTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentBinaryTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/transferobjects/")]
    public abstract partial class abstractVersionedTO : abstractReadWriteTO
    {
        
        private string rowIdField;
        
        private int rowVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rowId
        {
            get
            {
                return this.rowIdField;
            }
            set
            {
                this.rowIdField = value;
                this.RaisePropertyChanged("rowId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int rowVersion
        {
            get
            {
                return this.rowVersionField;
            }
            set
            {
                this.rowVersionField = value;
                this.RaisePropertyChanged("rowVersion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractVersionedTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractIdTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentBinaryTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/transferobjects/")]
    public abstract partial class abstractReadWriteTO : abstractTO
    {
        
        private entityAction entityActionField;
        
        private bool entityActionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public entityAction entityAction
        {
            get
            {
                return this.entityActionField;
            }
            set
            {
                this.entityActionField = value;
                this.RaisePropertyChanged("entityAction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool entityActionSpecified
        {
            get
            {
                return this.entityActionFieldSpecified;
            }
            set
            {
                this.entityActionFieldSpecified = value;
                this.RaisePropertyChanged("entityActionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/transferobjects/")]
    public enum entityAction
    {
        
        /// <remarks/>
        DELETE,
        
        /// <remarks/>
        DISASSOCIATE,
        
        /// <remarks/>
        INSERT,
        
        /// <remarks/>
        UPDATE,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractReadWriteTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractVersionedTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractIdTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentBinaryTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fileInfoTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fileBinaryTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/transferobjects/")]
    public abstract partial class abstractTO : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fileBinaryTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/transferobjects/digitalarchive/")]
    public partial class fileInfoTO : abstractTO
    {
        
        private long fileSizeField;
        
        private System.DateTime modificationDateField;
        
        private bool modificationDateFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long fileSize
        {
            get
            {
                return this.fileSizeField;
            }
            set
            {
                this.fileSizeField = value;
                this.RaisePropertyChanged("fileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime modificationDate
        {
            get
            {
                return this.modificationDateField;
            }
            set
            {
                this.modificationDateField = value;
                this.RaisePropertyChanged("modificationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modificationDateSpecified
        {
            get
            {
                return this.modificationDateFieldSpecified;
            }
            set
            {
                this.modificationDateFieldSpecified = value;
                this.RaisePropertyChanged("modificationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.sola.org/transferobjects/digitalarchive/")]
    public partial class fileBinaryTO : fileInfoTO
    {
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
    }
}
namespace org.sola.webservices.digitalarchive
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.sola.org/digitalarchive", ConfigurationName="org.sola.webservices.digitalarchive.DigitalArchive")]
    public interface DigitalArchive
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sola.org/digitalarchive/DigitalArchive/DeleteFileRequest", ReplyAction="http://webservices.sola.org/digitalarchive/DigitalArchive/DeleteFileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/DeleteFile/Fault/SOLAFa" +
            "ult", Name="SOLAFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/DeleteFile/Fault/Unhand" +
            "ledFault", Name="UnhandledFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/DeleteFile/Fault/SOLAAc" +
            "cessFault", Name="SOLAAccessFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        org.sola.webservices.digitalarchive.DeleteFileResponse DeleteFile(org.sola.webservices.digitalarchive.DeleteFileRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocumentRequest", ReplyAction="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocument/Fault/SO" +
            "LAFault", Name="SOLAFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocument/Fault/Un" +
            "handledFault", Name="UnhandledFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocument/Fault/Op" +
            "timisticLockingFault", Name="OptimisticLockingFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocument/Fault/SO" +
            "LAAccessFault", Name="SOLAAccessFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        org.sola.webservices.digitalarchive.CreateDocumentResponse CreateDocument(org.sola.webservices.digitalarchive.CreateDocumentRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocumentFromServe" +
            "rRequest", ReplyAction="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocumentFromServe" +
            "rResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocumentFromServe" +
            "r/Fault/SOLAFault", Name="SOLAFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocumentFromServe" +
            "r/Fault/UnhandledFault", Name="UnhandledFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocumentFromServe" +
            "r/Fault/OptimisticLockingFault", Name="OptimisticLockingFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CreateDocumentFromServe" +
            "r/Fault/SOLAAccessFault", Name="SOLAAccessFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        org.sola.webservices.digitalarchive.CreateDocumentFromServerResponse CreateDocumentFromServer(org.sola.webservices.digitalarchive.CreateDocumentFromServerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetFileBinaryRequest", ReplyAction="http://webservices.sola.org/digitalarchive/DigitalArchive/GetFileBinaryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetFileBinary/Fault/SOL" +
            "AFault", Name="SOLAFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetFileBinary/Fault/Unh" +
            "andledFault", Name="UnhandledFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetFileBinary/Fault/SOL" +
            "AAccessFault", Name="SOLAAccessFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        org.sola.webservices.digitalarchive.GetFileBinaryResponse GetFileBinary(org.sola.webservices.digitalarchive.GetFileBinaryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetFileThumbnailRequest" +
            "", ReplyAction="http://webservices.sola.org/digitalarchive/DigitalArchive/GetFileThumbnailRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetFileThumbnail/Fault/" +
            "SOLAFault", Name="SOLAFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetFileThumbnail/Fault/" +
            "UnhandledFault", Name="UnhandledFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetFileThumbnail/Fault/" +
            "SOLAAccessFault", Name="SOLAAccessFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        org.sola.webservices.digitalarchive.GetFileThumbnailResponse GetFileThumbnail(org.sola.webservices.digitalarchive.GetFileThumbnailRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sola.org/digitalarchive/DigitalArchive/CheckConnectionRequest", ReplyAction="http://webservices.sola.org/digitalarchive/DigitalArchive/CheckConnectionResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        org.sola.webservices.digitalarchive.CheckConnectionResponse CheckConnection(org.sola.webservices.digitalarchive.CheckConnectionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetAllFilesRequest", ReplyAction="http://webservices.sola.org/digitalarchive/DigitalArchive/GetAllFilesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetAllFiles/Fault/SOLAF" +
            "ault", Name="SOLAFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetAllFiles/Fault/Unhan" +
            "dledFault", Name="UnhandledFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetAllFiles/Fault/SOLAA" +
            "ccessFault", Name="SOLAAccessFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        org.sola.webservices.digitalarchive.GetAllFilesResponse GetAllFiles(org.sola.webservices.digitalarchive.GetAllFilesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sola.org/digitalarchive/DigitalArchive/SaveDocumentRequest", ReplyAction="http://webservices.sola.org/digitalarchive/DigitalArchive/SaveDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/SaveDocument/Fault/SOLA" +
            "Fault", Name="SOLAFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/SaveDocument/Fault/Unha" +
            "ndledFault", Name="UnhandledFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/SaveDocument/Fault/Opti" +
            "misticLockingFault", Name="OptimisticLockingFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/SaveDocument/Fault/SOLA" +
            "AccessFault", Name="SOLAAccessFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        org.sola.webservices.digitalarchive.SaveDocumentResponse SaveDocument(org.sola.webservices.digitalarchive.SaveDocumentRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetDocumentRequest", ReplyAction="http://webservices.sola.org/digitalarchive/DigitalArchive/GetDocumentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetDocument/Fault/SOLAF" +
            "ault", Name="SOLAFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetDocument/Fault/Unhan" +
            "dledFault", Name="UnhandledFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(org.sola.webservices.digitalarchive.extra.faultInfoBean), Action="http://webservices.sola.org/digitalarchive/DigitalArchive/GetDocument/Fault/SOLAA" +
            "ccessFault", Name="SOLAAccessFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        org.sola.webservices.digitalarchive.GetDocumentResponse GetDocument(org.sola.webservices.digitalarchive.GetDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteFile", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class DeleteFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        public DeleteFileRequest()
        {
        }
        
        public DeleteFileRequest(string fileName)
        {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteFileResponse", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class DeleteFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public DeleteFileResponse()
        {
        }
        
        public DeleteFileResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDocument", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class CreateDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public org.sola.webservices.digitalarchive.extra.documentBinaryTO documentTO;
        
        public CreateDocumentRequest()
        {
        }
        
        public CreateDocumentRequest(org.sola.webservices.digitalarchive.extra.documentBinaryTO documentTO)
        {
            this.documentTO = documentTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDocumentResponse", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class CreateDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public org.sola.webservices.digitalarchive.extra.documentTO @return;
        
        public CreateDocumentResponse()
        {
        }
        
        public CreateDocumentResponse(org.sola.webservices.digitalarchive.extra.documentTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDocumentFromServer", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class CreateDocumentFromServerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public org.sola.webservices.digitalarchive.extra.documentTO documentTO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        public CreateDocumentFromServerRequest()
        {
        }
        
        public CreateDocumentFromServerRequest(org.sola.webservices.digitalarchive.extra.documentTO documentTO, string fileName)
        {
            this.documentTO = documentTO;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDocumentFromServerResponse", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class CreateDocumentFromServerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public org.sola.webservices.digitalarchive.extra.documentTO @return;
        
        public CreateDocumentFromServerResponse()
        {
        }
        
        public CreateDocumentFromServerResponse(org.sola.webservices.digitalarchive.extra.documentTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileBinary", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class GetFileBinaryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        public GetFileBinaryRequest()
        {
        }
        
        public GetFileBinaryRequest(string fileName)
        {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileBinaryResponse", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class GetFileBinaryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public org.sola.webservices.digitalarchive.extra.fileInfoTO @return;
        
        public GetFileBinaryResponse()
        {
        }
        
        public GetFileBinaryResponse(org.sola.webservices.digitalarchive.extra.fileInfoTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileThumbnail", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class GetFileThumbnailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        public GetFileThumbnailRequest()
        {
        }
        
        public GetFileThumbnailRequest(string fileName)
        {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileThumbnailResponse", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class GetFileThumbnailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public org.sola.webservices.digitalarchive.extra.fileBinaryTO @return;
        
        public GetFileThumbnailResponse()
        {
        }
        
        public GetFileThumbnailResponse(org.sola.webservices.digitalarchive.extra.fileBinaryTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckConnection", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class CheckConnectionRequest
    {
        
        public CheckConnectionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckConnectionResponse", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class CheckConnectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public CheckConnectionResponse()
        {
        }
        
        public CheckConnectionResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllFiles", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class GetAllFilesRequest
    {
        
        public GetAllFilesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllFilesResponse", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class GetAllFilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public fileInfoTO[] @return;
        
        public GetAllFilesResponse()
        {
        }
        
        public GetAllFilesResponse(fileInfoTO[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveDocument", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class SaveDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public org.sola.webservices.digitalarchive.extra.documentTO documentTO;
        
        public SaveDocumentRequest()
        {
        }
        
        public SaveDocumentRequest(org.sola.webservices.digitalarchive.extra.documentTO documentTO)
        {
            this.documentTO = documentTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveDocumentResponse", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class SaveDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public org.sola.webservices.digitalarchive.extra.documentTO @return;
        
        public SaveDocumentResponse()
        {
        }
        
        public SaveDocumentResponse(org.sola.webservices.digitalarchive.extra.documentTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocument", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class GetDocumentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string documentId;
        
        public GetDocumentRequest()
        {
        }
        
        public GetDocumentRequest(string documentId)
        {
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentResponse", WrapperNamespace="http://webservices.sola.org/digitalarchive", IsWrapped=true)]
    public partial class GetDocumentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.sola.org/digitalarchive", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public org.sola.webservices.digitalarchive.extra.documentBinaryTO @return;
        
        public GetDocumentResponse()
        {
        }
        
        public GetDocumentResponse(org.sola.webservices.digitalarchive.extra.documentBinaryTO @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface DigitalArchiveChannel : org.sola.webservices.digitalarchive.DigitalArchive, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DigitalArchiveClient : System.ServiceModel.ClientBase<org.sola.webservices.digitalarchive.DigitalArchive>, org.sola.webservices.digitalarchive.DigitalArchive
    {
        
        public DigitalArchiveClient()
        {
        }
        
        public DigitalArchiveClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DigitalArchiveClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DigitalArchiveClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DigitalArchiveClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.sola.webservices.digitalarchive.DeleteFileResponse org.sola.webservices.digitalarchive.DigitalArchive.DeleteFile(org.sola.webservices.digitalarchive.DeleteFileRequest request)
        {
            return base.Channel.DeleteFile(request);
        }
        
        public bool DeleteFile(string fileName)
        {
            org.sola.webservices.digitalarchive.DeleteFileRequest inValue = new org.sola.webservices.digitalarchive.DeleteFileRequest();
            inValue.fileName = fileName;
            org.sola.webservices.digitalarchive.DeleteFileResponse retVal = ((org.sola.webservices.digitalarchive.DigitalArchive)(this)).DeleteFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.sola.webservices.digitalarchive.CreateDocumentResponse org.sola.webservices.digitalarchive.DigitalArchive.CreateDocument(org.sola.webservices.digitalarchive.CreateDocumentRequest request)
        {
            return base.Channel.CreateDocument(request);
        }
        
        public org.sola.webservices.digitalarchive.extra.documentTO CreateDocument(org.sola.webservices.digitalarchive.extra.documentBinaryTO documentTO)
        {
            org.sola.webservices.digitalarchive.CreateDocumentRequest inValue = new org.sola.webservices.digitalarchive.CreateDocumentRequest();
            inValue.documentTO = documentTO;
            org.sola.webservices.digitalarchive.CreateDocumentResponse retVal = ((org.sola.webservices.digitalarchive.DigitalArchive)(this)).CreateDocument(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.sola.webservices.digitalarchive.CreateDocumentFromServerResponse org.sola.webservices.digitalarchive.DigitalArchive.CreateDocumentFromServer(org.sola.webservices.digitalarchive.CreateDocumentFromServerRequest request)
        {
            return base.Channel.CreateDocumentFromServer(request);
        }
        
        public org.sola.webservices.digitalarchive.extra.documentTO CreateDocumentFromServer(org.sola.webservices.digitalarchive.extra.documentTO documentTO, string fileName)
        {
            org.sola.webservices.digitalarchive.CreateDocumentFromServerRequest inValue = new org.sola.webservices.digitalarchive.CreateDocumentFromServerRequest();
            inValue.documentTO = documentTO;
            inValue.fileName = fileName;
            org.sola.webservices.digitalarchive.CreateDocumentFromServerResponse retVal = ((org.sola.webservices.digitalarchive.DigitalArchive)(this)).CreateDocumentFromServer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.sola.webservices.digitalarchive.GetFileBinaryResponse org.sola.webservices.digitalarchive.DigitalArchive.GetFileBinary(org.sola.webservices.digitalarchive.GetFileBinaryRequest request)
        {
            return base.Channel.GetFileBinary(request);
        }
        
        public org.sola.webservices.digitalarchive.extra.fileInfoTO GetFileBinary(string fileName)
        {
            org.sola.webservices.digitalarchive.GetFileBinaryRequest inValue = new org.sola.webservices.digitalarchive.GetFileBinaryRequest();
            inValue.fileName = fileName;
            org.sola.webservices.digitalarchive.GetFileBinaryResponse retVal = ((org.sola.webservices.digitalarchive.DigitalArchive)(this)).GetFileBinary(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.sola.webservices.digitalarchive.GetFileThumbnailResponse org.sola.webservices.digitalarchive.DigitalArchive.GetFileThumbnail(org.sola.webservices.digitalarchive.GetFileThumbnailRequest request)
        {
            return base.Channel.GetFileThumbnail(request);
        }
        
        public org.sola.webservices.digitalarchive.extra.fileBinaryTO GetFileThumbnail(string fileName)
        {
            org.sola.webservices.digitalarchive.GetFileThumbnailRequest inValue = new org.sola.webservices.digitalarchive.GetFileThumbnailRequest();
            inValue.fileName = fileName;
            org.sola.webservices.digitalarchive.GetFileThumbnailResponse retVal = ((org.sola.webservices.digitalarchive.DigitalArchive)(this)).GetFileThumbnail(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.sola.webservices.digitalarchive.CheckConnectionResponse org.sola.webservices.digitalarchive.DigitalArchive.CheckConnection(org.sola.webservices.digitalarchive.CheckConnectionRequest request)
        {
            return base.Channel.CheckConnection(request);
        }
        
        public bool CheckConnection()
        {
            org.sola.webservices.digitalarchive.CheckConnectionRequest inValue = new org.sola.webservices.digitalarchive.CheckConnectionRequest();
            org.sola.webservices.digitalarchive.CheckConnectionResponse retVal = ((org.sola.webservices.digitalarchive.DigitalArchive)(this)).CheckConnection(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.sola.webservices.digitalarchive.GetAllFilesResponse org.sola.webservices.digitalarchive.DigitalArchive.GetAllFiles(org.sola.webservices.digitalarchive.GetAllFilesRequest request)
        {
            return base.Channel.GetAllFiles(request);
        }
        
        public fileInfoTO[] GetAllFiles()
        {
            org.sola.webservices.digitalarchive.GetAllFilesRequest inValue = new org.sola.webservices.digitalarchive.GetAllFilesRequest();
            org.sola.webservices.digitalarchive.GetAllFilesResponse retVal = ((org.sola.webservices.digitalarchive.DigitalArchive)(this)).GetAllFiles(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.sola.webservices.digitalarchive.SaveDocumentResponse org.sola.webservices.digitalarchive.DigitalArchive.SaveDocument(org.sola.webservices.digitalarchive.SaveDocumentRequest request)
        {
            return base.Channel.SaveDocument(request);
        }
        
        public org.sola.webservices.digitalarchive.extra.documentTO SaveDocument(org.sola.webservices.digitalarchive.extra.documentTO documentTO)
        {
            org.sola.webservices.digitalarchive.SaveDocumentRequest inValue = new org.sola.webservices.digitalarchive.SaveDocumentRequest();
            inValue.documentTO = documentTO;
            org.sola.webservices.digitalarchive.SaveDocumentResponse retVal = ((org.sola.webservices.digitalarchive.DigitalArchive)(this)).SaveDocument(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.sola.webservices.digitalarchive.GetDocumentResponse org.sola.webservices.digitalarchive.DigitalArchive.GetDocument(org.sola.webservices.digitalarchive.GetDocumentRequest request)
        {
            return base.Channel.GetDocument(request);
        }
        
        public org.sola.webservices.digitalarchive.extra.documentBinaryTO GetDocument(string documentId)
        {
            org.sola.webservices.digitalarchive.GetDocumentRequest inValue = new org.sola.webservices.digitalarchive.GetDocumentRequest();
            inValue.documentId = documentId;
            org.sola.webservices.digitalarchive.GetDocumentResponse retVal = ((org.sola.webservices.digitalarchive.DigitalArchive)(this)).GetDocument(inValue);
            return retVal.@return;
        }
    }
}
